service: email-verifier-serverless-api

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  timeout: 30

functions:
  verify:
    handler: controller/email.handler
    events:
      - http: OPTIONS /verify
      - http: POST /verify  

plugins:
  - serverless-offline
